### ISSUE TITLE
Command URL not working

### ISSUE THREAD

**Issue by bobaroo27** [polispay/polis-doc#1]
the url for this command given is returning an error 404 message when entered into the VPS. Any advise?

**Comment by nhd90** [comment]
Me too !
VPS Setup : URL didn't work !

**Comment by pulijalahari** [comment]
i tried with command "wget https://github.com/polispay/polis-doc/blob/master/masternode-setup/install_masternode.sh && chmod +x install_masternode.sh && ./install_masternode.sh" and it worked fine but there was an error ./install_masternode.sh: line 7: syntax error near unexpected token `newline'
./install_masternode.sh: line 7: `<!DOCTYPE html>'

Any Devs who can help fix this?

**Comment by pulijalahari** [comment]
the url is wrong but use the above url. if any one having the issue like me after putting correct url , please let me know how to fix it

**Comment by pulijalahari** [comment]
Friends: I could fix the issue by doing the following.
instead of the command given here, do.
1) nano install_masternode.sh
2) copy the text from the file here : https://github.com/polispay/polis-doc/blob/master/masternode-setup/install_masternode.sh
3) once saved, do chmod +x install_masternode.sh && ./install_masternode.sh

if you like this, please donate BTC at 16sy1CNkrzyXxt8NbRCNnWkmuxxyo8sih1

**Comment by bobaroo27** [comment]
i will try. Any tips on enabling copy/paste from host to console for mac? I have been unsuccessful so far.

**Comment by Zacorich** [comment]
Does network experiencing some issues right now? Also block explorer doesn't work .

**Comment by claybuttz** [comment]
This is what i'm getting:

./install_masternode.sh: line 7: syntax error near unexpected token `newline'
./install_masternode.sh: line 7: `<!DOCTYPE html>'

How to fix?

**Comment by bobaroo27** [comment]
Follow pulijalahari process, that ended up working. Does anyone have feedback on how long it takes the node to start working or payments to come in?

**Comment by pulijalahari** [comment]
payments come about in a day

**Comment by tech1e** [comment]
Thank you for raising the URL issue and helping the community 🚀 
This fix has been merged in master.
