### ISSUE TITLE
latest version(?) not working

### ISSUE THREAD

**Issue by rust4545** [polispay/polis-doc#11]
1) The script is instaling version poliscore-1-1-0  but here is already a version 1-2-0
Is that intentional?

2) unzip is not installed using apt-get
so on a new vps this script will fail to unpack and move essential files
error in the installer:
./install_masternode.sh: line 124: unzip: command not found

3) path referenced in the mv command is incorrect
mv: cannot stat '/root/poliscore-1.1.0/usr/local/bin/polisd': No such file or directory
mv: cannot stat '/root/poliscore-1.1.0/usr/local/bin/polis-cli': No such file or directory

the path is poliscore-1.1.0-linux
and not poliscore-1.1.0

**Comment by phips28** [comment]
PR fix: https://github.com/polispay/polis-doc/pull/12

**Comment by polispay** [comment]
Merged.
