### ISSUE TITLE
line 7: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by raviNalliyappa** [polispay/polis-doc#2]
I get the error below. Any suggestions ? 

./install_masternode.sh: line 7: syntax error near unexpected token `newline'
./install_masternode.sh: line 7: `<!DOCTYPE html>'

**Comment by raviNalliyappa** [comment]
Someone gave solution in the other window and it works for me. Take the following steps
1. nano install_masternode.sh
2. copy the text from the file here : https://github.com/polispay/polis-doc/blob/master/masternode-setup/install_masternode.sh
3. once saved, do chmod +x install_masternode.sh && ./install_masternode.sh

**Comment by tech1e** [comment]
This has been addressed here: https://github.com/polispay/polis-doc/pull/3

Thank you for raising the issue and helping the community 🚀

**Comment by raviNalliyappa** [comment]
thanks
