### ISSUE TITLE
Master node restart

### ISSUE THREAD

**Issue by AndAntAnd** [polispay/polis-doc#24]
After restart of masternode no payments for over 3 days. What could be the reason?

polis-cli masternode status - "masternode successfully started"
wallet also shows status ENABLED.

Restart was done only on wallet side.

Shall VPS side be changed to 1.3.0 or 1.2.2. still ok?

**Comment by cronos-polis** [comment]
Both versions are ok.
You can use 1.2.2 or 1.3.0. Just  make sure your masternode is ENABLED on multiple MNList. You can look on polis.mn.zone
