### ISSUE TITLE
SENTINEL_PING_EXPIRED

### ISSUE THREAD

**Issue by izoomrud** [polispay/polis-doc#25]
When i start the wallet is always a status ENABLE, then it changes to SENTINEL_PING_EXPIRED, masternode monitoring always shows a SENTINEL_PING_EXPIRED, on the server I check the node `polis-cli masternode status` and get  "status": "Masternode successfully started",  what's the problem?

**Comment by ErosPolis** [comment]
Wait like 4-5 hours and check again. If the problem persists, please contact tech support in the discord channel: https://discord.gg/c9AxPrk
