### ISSUE TITLE
My Masternode is stuck in WATCHDOG_EXPIRED mode

### ISSUE THREAD

**Issue by raviNalliyappa** [polispay/polis-doc#4]
Hi, I created a masternode using the given guide. Thanks a lot for the guide it was very clear. But my MasterNode stays in  WATCHDOG_EXPIRED mode for several hours before changing to Expired mode. Every time I restart the node, I get the same issue. I've tried it several times since yesterday. Any help will be appreciated and I will be happy to buy you a cup of coffee :-)

**Comment by polispay** [comment]
Make sure you installed sentinel correctly.
https://github.com/polispay/sentinel
