### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by youngfoung** [polispay/polis-doc#9]
I've gone through step 5 of VPS setup

I get two errors:

Installing poliscore-1.0.0...
mv: cannot stat '/root/poliscore-1.1.0/usr/local/bin/polisd': No such file or directory
mv: cannot stat '/root/poliscore-1.1.0/usr/local/bin/polis-cli': No such file or directory

I think that because of that when I try to run:
polis-cli getinfo

It doesn't work. Any help would be greatly appreciated!

**Comment by phips28** [comment]
PR fix: https://github.com/polispay/polis-doc/pull/12

**Comment by polispay** [comment]
Merged.
